site_name: Laravel Meilisearch Documentation
site_url: https://jaihreal.github.io/laravel-meilisearch-docs
theme:
  name: material
  font:
    # text: Roboto
    code: Red Hat Mono
  logo: assets/img/logo/amlakas.webp
  favicon: assets/img/favicon.ico

  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: default
      accent: default

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: white

  features:
    # - navigation.tabs
    # - navigation.sections
    # - navigation.top
    # - toc.integrate
    # - navigation.footer

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

  - toc:
      # permalink: true
      # toc_depth: 1

extra_javascript:
  - assets/js/smooth-scroll.js

extra:
  social:
    # - icon: assets/img/logo/amlakas.webp
    #   link: https://portal.amlakas.com/login
    - icon: simple/facebook
      link: https://facebook.com
    - icon: simple/youtube
      link: https://youtube.com
# copyright: Copyright &copy; 2025 Jaih Real Sasing
